### ISSUE TITLE
Add test to check whether all columns needed are in process_metadata_file

### ISSUE THREAD

**Issue by KristinaGomoryova** [RECETOX/rcx-tk#14]
Write a test which will assess whether all columns required for process_metadata_file are present, ie.

`columns_to_keep = {
        'File name': 'sampleName',
        'Type': 'sampleType',
        'Class ID': 'class',
        'Batch': 'batch',
        'Analytical order': 'injectionOrder'
    }`

**Comment by hechth** [comment]
@KristinaGomoryova please check if this is actually handled by now, because I think it is :)

**Comment by KristinaGomoryova** [comment]
It is indeed here: c9dc679 :)
This closes #14
